services:
  db:
    image: postgres:17.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: social
    volumes:
      - .docker/db/postgres_data:/var/lib/postgresql/data
